window.DATA = [
  {
    "tense": "Present",
    "form": "Affirmative",
    "subject": "I (eu)",
    "verb": "am (sou/estou)",
    "play1": "I am",
    "pron1": "ái ém",
    "play2": "I'm",
    "pron2": "áim",
    "hint": "Ex: eu sou/estou"
  },
  {
    "tense": "Present",
    "form": "Negative",
    "subject": "I (eu)",
    "verb": "am not (não sou/estou)",
    "play1": "I am not",
    "pron1": "ái ém nót",
    "play2": "I'm not",
    "pron2": "áim nót",
    "hint": "Ex: eu não sou/estou"
  },
  {
    "tense": "Present",
    "form": "Question",
    "subject": "I (eu)",
    "verb": "am (sou/estou)",
    "play1": "am I",
    "pron1": "ém ái",
    "play2": "",
    "pron2": "",
    "hint": "Ex: eu sou/estou?"
  },
  {
    "tense": "Present",
    "form": "Negative Question",
    "subject": "I not (eu não)",
    "verb": "am (sou/estou)",
    "play1": "am I not",
    "pron1": "ém ái nót",
    "play2": "Aren't I",
    "pron2": "Árnt ái",
    "hint": "Ex: eu não sou/estou?"
  },
  {
    "tense": "Present",
    "form": "Affirmative",
    "subject": "You (você/vocês)",
    "verb": "are (são/estão)",
    "play1": "You are",
    "pron1": "iú ar",
    "play2": "You're",
    "pron2": "iór",
    "hint": "Ex: você são/estão"
  },
  {
    "tense": "Present",
    "form": "Negative",
    "subject": "You (você/vocês)",
    "verb": "are not (não é/está/são/estão)",
    "play1": "You are not",
    "pron1": "iú ar nót",
    "play2": "You aren't",
    "pron2": "iú árnt",
    "hint": "Ex: você não é/está"
  },
  {
    "tense": "Present",
    "form": "Question",
    "subject": "You (você/vocês)",
    "verb": "are (são/estão)",
    "play1": "are You",
    "pron1": "ar iú",
    "play2": "",
    "pron2": "",
    "hint": "Ex: você são/estão?"
  },
  {
    "tense": "Present",
    "form": "Negative Question",
    "subject": "You not (você/vocês não)",
    "verb": "are (são/estão)",
    "play1": "are You not",
    "pron1": "ar iú nót",
    "play2": "Aren't You",
    "pron2": "Árnt iú",
    "hint": "Ex: você não são/estão?"
  },
  {
    "tense": "Present",
    "form": "Affirmative",
    "subject": "He (ele)",
    "verb": "is (é/está)",
    "play1": "He is",
    "pron1": "rí íz",
    "play2": "He's",
    "pron2": "ríz",
    "hint": "Ex: ele é/está"
  },
  {
    "tense": "Present",
    "form": "Negative",
    "subject": "He (ele)",
    "verb": "is not (não é/está)",
    "play1": "He is not",
    "pron1": "rí íz nót",
    "play2": "He isn't",
    "pron2": "rí íznt",
    "hint": "Ex: ele não é/está"
  },
  {
    "tense": "Present",
    "form": "Question",
    "subject": "He (ele)",
    "verb": "is (é/está)",
    "play1": "is He",
    "pron1": "íz rí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ele é/está?"
  },
  {
    "tense": "Present",
    "form": "Negative Question",
    "subject": "He not (ele não)",
    "verb": "is (é/está)",
    "play1": "is He not",
    "pron1": "íz rí nót",
    "play2": "Isn't He",
    "pron2": "Íznt rí",
    "hint": "Ex: ele não é/está?"
  },
  {
    "tense": "Present",
    "form": "Affirmative",
    "subject": "She (ela)",
    "verb": "is (é/está)",
    "play1": "She is",
    "pron1": "xí íz",
    "play2": "She's",
    "pron2": "xíz",
    "hint": "Ex: ela é/está"
  },
  {
    "tense": "Present",
    "form": "Negative",
    "subject": "She (ela)",
    "verb": "is not (não é/está)",
    "play1": "She is not",
    "pron1": "xí íz nót",
    "play2": "She isn't",
    "pron2": "xí íznt",
    "hint": "Ex: ela não é/está"
  },
  {
    "tense": "Present",
    "form": "Question",
    "subject": "She (ela)",
    "verb": "is (é/está)",
    "play1": "is She",
    "pron1": "íz xí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ela é/está?"
  },
  {
    "tense": "Present",
    "form": "Negative Question",
    "subject": "She not (ela não)",
    "verb": "is (é/está)",
    "play1": "is She not",
    "pron1": "íz xí nót",
    "play2": "Isn't She",
    "pron2": "Íznt xí",
    "hint": "Ex: ela não é/está?"
  },
  {
    "tense": "Present",
    "form": "Affirmative",
    "subject": "It (ele/ela/coisa)",
    "verb": "is (é/está)",
    "play1": "It is",
    "pron1": "ít íz",
    "play2": "It's",
    "pron2": "íts",
    "hint": "Ex: ele é/está"
  },
  {
    "tense": "Present",
    "form": "Negative",
    "subject": "It (ele/ela/coisa)",
    "verb": "is not (não é/está)",
    "play1": "It is not",
    "pron1": "ít íz nót",
    "play2": "It isn't",
    "pron2": "ít íznt",
    "hint": "Ex: ele não é/está"
  },
  {
    "tense": "Present",
    "form": "Question",
    "subject": "It (ele/ela/coisa)",
    "verb": "is (é/está)",
    "play1": "is It",
    "pron1": "íz ít",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ele é/está?"
  },
  {
    "tense": "Present",
    "form": "Negative Question",
    "subject": "It not (ele/ela/coisa não)",
    "verb": "is (é/está)",
    "play1": "is It not",
    "pron1": "íz ít nót",
    "play2": "Isn't It",
    "pron2": "Íznt ít",
    "hint": "Ex: ele não é/está?"
  },
  {
    "tense": "Present",
    "form": "Affirmative",
    "subject": "We (nós)",
    "verb": "are (são/estão)",
    "play1": "We are",
    "pron1": "uí ar",
    "play2": "We're",
    "pron2": "uír",
    "hint": "Ex: nós são/estão"
  },
  {
    "tense": "Present",
    "form": "Negative",
    "subject": "We (nós)",
    "verb": "are not (não é/está/são/estão)",
    "play1": "We are not",
    "pron1": "uí ar nót",
    "play2": "We aren't",
    "pron2": "uí árnt",
    "hint": "Ex: nós não é/está"
  },
  {
    "tense": "Present",
    "form": "Question",
    "subject": "We (nós)",
    "verb": "are (são/estão)",
    "play1": "are We",
    "pron1": "ar uí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: nós são/estão?"
  },
  {
    "tense": "Present",
    "form": "Negative Question",
    "subject": "We not (nós não)",
    "verb": "are (são/estão)",
    "play1": "are We not",
    "pron1": "ar uí nót",
    "play2": "Aren't We",
    "pron2": "Árnt uí",
    "hint": "Ex: nós não são/estão?"
  },
  {
    "tense": "Present",
    "form": "Affirmative",
    "subject": "They (eles/elas)",
    "verb": "are (são/estão)",
    "play1": "They are",
    "pron1": "dêir ar",
    "play2": "They're",
    "pron2": "They're",
    "hint": "Ex: eles são/estão"
  },
  {
    "tense": "Present",
    "form": "Negative",
    "subject": "They (eles/elas)",
    "verb": "are not (não é/está/são/estão)",
    "play1": "They are not",
    "pron1": "têir ór nóti",
    "play2": "They aren't",
    "pron2": "dêir árnt",
    "hint": "Ex: eles/elas não é/está/são/estão"
  },
  {
    "tense": "Present",
    "form": "Question",
    "subject": "They (eles/elas)",
    "verb": "are (são/estão)",
    "play1": "are They",
    "pron1": "ar dêir",
    "play2": "",
    "pron2": "",
    "hint": "Ex: eles são/estão?"
  },
  {
    "tense": "Present",
    "form": "Negative Question",
    "subject": "They not (eles/elas não)",
    "verb": "are (são/estão)",
    "play1": "are They not",
    "pron1": "ar dêir nót",
    "play2": "Aren't They",
    "pron2": "Árnt dêir",
    "hint": "Ex: eles não são/estão?"
  },
  {
    "tense": "Past",
    "form": "Affirmative",
    "subject": "I (eu)",
    "verb": "was (era/estava)",
    "play1": "I was",
    "pron1": "ái uóz",
    "play2": "",
    "pron2": "",
    "hint": "Ex: eu era"
  },
  {
    "tense": "Past",
    "form": "Negative",
    "subject": "I (eu)",
    "verb": "was not (não era/estava)",
    "play1": "I was not",
    "pron1": "ái uóz nót",
    "play2": "I wasn't",
    "pron2": "ái uóznt",
    "hint": "Ex: eu não era"
  },
  {
    "tense": "Past",
    "form": "Question",
    "subject": "I (eu)",
    "verb": "was (era/estava)",
    "play1": "was I",
    "pron1": "uóz ái",
    "play2": "",
    "pron2": "",
    "hint": "Ex: eu era?"
  },
  {
    "tense": "Past",
    "form": "Negative Question",
    "subject": "I not (eu não)",
    "verb": "was (era/estava)",
    "play1": "was I not",
    "pron1": "uóz ái nót",
    "play2": "Wasn't I",
    "pron2": "Uóznt ái",
    "hint": "Ex: eu não era?"
  },
  {
    "tense": "Past",
    "form": "Affirmative",
    "subject": "You (você/vocês)",
    "verb": "were (eram/estavam)",
    "play1": "You were",
    "pron1": "iú uâr",
    "play2": "",
    "pron2": "",
    "hint": "Ex: você eram"
  },
  {
    "tense": "Past",
    "form": "Negative",
    "subject": "You (você/vocês)",
    "verb": "were not (não eram/estavam)",
    "play1": "You were not",
    "pron1": "iú uâr nót",
    "play2": "You weren't",
    "pron2": "iú uârnt",
    "hint": "Ex: você não eram"
  },
  {
    "tense": "Past",
    "form": "Question",
    "subject": "You (você/vocês)",
    "verb": "were (eram/estavam)",
    "play1": "were You",
    "pron1": "uâr iú",
    "play2": "",
    "pron2": "",
    "hint": "Ex: você eram?"
  },
  {
    "tense": "Past",
    "form": "Negative Question",
    "subject": "You not (você/vocês não)",
    "verb": "were (eram/estavam)",
    "play1": "were You not",
    "pron1": "uâr iú nót",
    "play2": "Weren't You",
    "pron2": "Uârnt iú",
    "hint": "Ex: você não eram?"
  },
  {
    "tense": "Past",
    "form": "Affirmative",
    "subject": "He (ele)",
    "verb": "was (era/estava)",
    "play1": "He was",
    "pron1": "rí uóz",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ele era"
  },
  {
    "tense": "Past",
    "form": "Negative",
    "subject": "He (ele)",
    "verb": "was not (não era/estava)",
    "play1": "He was not",
    "pron1": "rí uóz nót",
    "play2": "He wasn't",
    "pron2": "rí uóznt",
    "hint": "Ex: ele não era"
  },
  {
    "tense": "Past",
    "form": "Question",
    "subject": "He (ele)",
    "verb": "was (era/estava)",
    "play1": "was He",
    "pron1": "uóz rí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ele era?"
  },
  {
    "tense": "Past",
    "form": "Negative Question",
    "subject": "He not (ele não)",
    "verb": "was (era/estava)",
    "play1": "was He not",
    "pron1": "uóz rí nót",
    "play2": "Wasn't He",
    "pron2": "Uóznt rí",
    "hint": "Ex: ele não era?"
  },
  {
    "tense": "Past",
    "form": "Affirmative",
    "subject": "She (ela)",
    "verb": "was (era/estava)",
    "play1": "She was",
    "pron1": "xí uóz",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ela era"
  },
  {
    "tense": "Past",
    "form": "Negative",
    "subject": "She (ela)",
    "verb": "was not (não era/estava)",
    "play1": "She was not",
    "pron1": "xí uóz nót",
    "play2": "She wasn't",
    "pron2": "xí uóznt",
    "hint": "Ex: ela não era"
  },
  {
    "tense": "Past",
    "form": "Question",
    "subject": "She (ela)",
    "verb": "was (era/estava)",
    "play1": "was She",
    "pron1": "uóz xí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ela era?"
  },
  {
    "tense": "Past",
    "form": "Negative Question",
    "subject": "She not (ela não)",
    "verb": "was (era/estava)",
    "play1": "was She not",
    "pron1": "uóz xí nót",
    "play2": "Wasn't She",
    "pron2": "Uóznt xí",
    "hint": "Ex: ela não era?"
  },
  {
    "tense": "Past",
    "form": "Affirmative",
    "subject": "It (ele/ela/coisa)",
    "verb": "was (era/estava)",
    "play1": "It was",
    "pron1": "ít uóz",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ele era"
  },
  {
    "tense": "Past",
    "form": "Negative",
    "subject": "It (ele/ela/coisa)",
    "verb": "was not (não era/estava)",
    "play1": "It was not",
    "pron1": "ít uóz nót",
    "play2": "It wasn't",
    "pron2": "ít uóznt",
    "hint": "Ex: ele não era"
  },
  {
    "tense": "Past",
    "form": "Question",
    "subject": "It (ele/ela/coisa)",
    "verb": "was (era/estava)",
    "play1": "was It",
    "pron1": "uóz ít",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ele era?"
  },
  {
    "tense": "Past",
    "form": "Negative Question",
    "subject": "It not (ele/ela/coisa não)",
    "verb": "was (era/estava)",
    "play1": "was It not",
    "pron1": "uóz ít nót",
    "play2": "Wasn't It",
    "pron2": "Uóznt ít",
    "hint": "Ex: ele não era?"
  },
  {
    "tense": "Past",
    "form": "Affirmative",
    "subject": "We (nós)",
    "verb": "were (éramos/estávamos)",
    "play1": "We were",
    "pron1": "uí uâr",
    "play2": "",
    "pron2": "",
    "hint": "Ex: nós éramos"
  },
  {
    "tense": "Past",
    "form": "Negative",
    "subject": "We (nós)",
    "verb": "were not (não éramos/estávamos)",
    "play1": "We were not",
    "pron1": "uí uâr nót",
    "play2": "We weren't",
    "pron2": "uí uârnt",
    "hint": "Ex: nós não éramos"
  },
  {
    "tense": "Past",
    "form": "Question",
    "subject": "We (nós)",
    "verb": "were (éramos/estávamos)",
    "play1": "were We",
    "pron1": "uâr uí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: nós éramos?"
  },
  {
    "tense": "Past",
    "form": "Negative Question",
    "subject": "We not (nós não)",
    "verb": "were (éramos/estávamos)",
    "play1": "were We not",
    "pron1": "uâr uí nót",
    "play2": "Weren't We",
    "pron2": "Uârnt uí",
    "hint": "Ex: nós não éramos?"
  },
  {
    "tense": "Past",
    "form": "Affirmative",
    "subject": "They (eles/elas)",
    "verb": "were (eram/estavam)",
    "play1": "They were",
    "pron1": "dêir uâr",
    "play2": "",
    "pron2": "",
    "hint": "Ex: eles eram"
  },
  {
    "tense": "Past",
    "form": "Negative",
    "subject": "They (eles/elas)",
    "verb": "were not (não eram/estavam)",
    "play1": "They were not",
    "pron1": "dêir uâr nót",
    "play2": "They weren't",
    "pron2": "dêir uârnt",
    "hint": "Ex: eles não eram"
  },
  {
    "tense": "Past",
    "form": "Question",
    "subject": "They (eles/elas)",
    "verb": "were (eram/estavam)",
    "play1": "were They",
    "pron1": "uâr dêir",
    "play2": "",
    "pron2": "",
    "hint": "Ex: eles eram?"
  },
  {
    "tense": "Past",
    "form": "Negative Question",
    "subject": "They not (eles/elas não)",
    "verb": "were (eram/estavam)",
    "play1": "were They not",
    "pron1": "uâr dêir nót",
    "play2": "Weren't They",
    "pron2": "Uârnt dêir",
    "hint": "Ex: eles não eram?"
  },
  {
    "tense": "Future",
    "form": "Affirmative",
    "subject": "I (eu)",
    "verb": "will be (serei/estarei)",
    "play1": "I will be",
    "pron1": "ái uíl bí",
    "play2": "I'll be",
    "pron2": "áil bí",
    "hint": "Ex: eu serei/estarei"
  },
  {
    "tense": "Future",
    "form": "Negative",
    "subject": "I (eu)",
    "verb": "will not be (não serei/estarei)",
    "play1": "I will not be",
    "pron1": "ái uíl nót bí",
    "play2": "Won't I be",
    "pron2": "Uôunt ái bí",
    "hint": "Ex: eu não serei/estarei"
  },
  {
    "tense": "Future",
    "form": "Question",
    "subject": "I (eu)",
    "verb": "will be (serei/estarei)",
    "play1": "Will I be",
    "pron1": "Uíl ái bí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: eu serei/estarei?"
  },
  {
    "tense": "Future",
    "form": "Negative Question",
    "subject": "I not (eu não)",
    "verb": "will be (serei/estarei)",
    "play1": "Will I not be",
    "pron1": "Uíl ái nót bí",
    "play2": "Won't I be",
    "pron2": "Uôunt ái bí",
    "hint": "Ex: eu não serei/estarei?"
  },
  {
    "tense": "Future",
    "form": "Affirmative",
    "subject": "You (você/vocês)",
    "verb": "will be (será/estará; serão/estarão)",
    "play1": "You will be",
    "pron1": "iú uíl bí",
    "play2": "You'll be",
    "pron2": "iúl bí",
    "hint": "Ex: você será/estará"
  },
  {
    "tense": "Future",
    "form": "Negative",
    "subject": "You (você/vocês)",
    "verb": "will not be (não será/estará; serão/estarão)",
    "play1": "You will not be",
    "pron1": "iú uíl nót bí",
    "play2": "Won't You be",
    "pron2": "Uôunt iú bí",
    "hint": "Ex: você não será/estará"
  },
  {
    "tense": "Future",
    "form": "Question",
    "subject": "You (você/vocês)",
    "verb": "will be (será/estará; serão/estarão)",
    "play1": "Will You be",
    "pron1": "Uíl iú bí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: você será/estará?"
  },
  {
    "tense": "Future",
    "form": "Negative Question",
    "subject": "You not (você/vocês não)",
    "verb": "will be (será/estará; serão/estarão)",
    "play1": "Will You not be",
    "pron1": "Uíl iú nót bí",
    "play2": "Won't You be",
    "pron2": "Uôunt iú bí",
    "hint": "Ex: você não será/estará?"
  },
  {
    "tense": "Future",
    "form": "Affirmative",
    "subject": "He (ele)",
    "verb": "will be (será/estará)",
    "play1": "He will be",
    "pron1": "rí uíl bí",
    "play2": "He'll be",
    "pron2": "ríl bí",
    "hint": "Ex: ele será/estará"
  },
  {
    "tense": "Future",
    "form": "Negative",
    "subject": "He (ele)",
    "verb": "will not be (não será/estará)",
    "play1": "He will not be",
    "pron1": "rí uíl nót bí",
    "play2": "Won't He be",
    "pron2": "Uôunt rí bí",
    "hint": "Ex: ele não será/estará"
  },
  {
    "tense": "Future",
    "form": "Question",
    "subject": "He (ele)",
    "verb": "will be (será/estará)",
    "play1": "Will He be",
    "pron1": "Uíl rí bí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ele será/estará?"
  },
  {
    "tense": "Future",
    "form": "Negative Question",
    "subject": "He not (ele não)",
    "verb": "will be (será/estará)",
    "play1": "Will He not be",
    "pron1": "Uíl rí nót bí",
    "play2": "Won't He be",
    "pron2": "Uôunt rí bí",
    "hint": "Ex: ele não será/estará?"
  },
  {
    "tense": "Future",
    "form": "Affirmative",
    "subject": "She (ela)",
    "verb": "will be (será/estará)",
    "play1": "She will be",
    "pron1": "xí uíl bí",
    "play2": "She'll be",
    "pron2": "xíl bí",
    "hint": "Ex: ela será/estará"
  },
  {
    "tense": "Future",
    "form": "Negative",
    "subject": "She (ela)",
    "verb": "will not be (não será/estará)",
    "play1": "She will not be",
    "pron1": "xí uíl nót bí",
    "play2": "Won't She be",
    "pron2": "Uôunt xí bí",
    "hint": "Ex: ela não será/estará"
  },
  {
    "tense": "Future",
    "form": "Question",
    "subject": "She (ela)",
    "verb": "will be (será/estará)",
    "play1": "Will She be",
    "pron1": "Uíl xí bí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ela será/estará?"
  },
  {
    "tense": "Future",
    "form": "Negative Question",
    "subject": "She not (ela não)",
    "verb": "will be (será/estará)",
    "play1": "Will She not be",
    "pron1": "Uíl xí nót bí",
    "play2": "Won't She be",
    "pron2": "Uôunt xí bí",
    "hint": "Ex: ela não será/estará?"
  },
  {
    "tense": "Future",
    "form": "Affirmative",
    "subject": "It (ele/ela/coisa)",
    "verb": "will be (será/estará)",
    "play1": "It will be",
    "pron1": "ít uíl bí",
    "play2": "It'll be",
    "pron2": "ítl bí",
    "hint": "Ex: ele será/estará"
  },
  {
    "tense": "Future",
    "form": "Negative",
    "subject": "It (ele/ela/coisa)",
    "verb": "will not be (não será/estará)",
    "play1": "It will not be",
    "pron1": "ít uíl nót bí",
    "play2": "Won't It be",
    "pron2": "Uôunt ít bí",
    "hint": "Ex: ele não será/estará"
  },
  {
    "tense": "Future",
    "form": "Question",
    "subject": "It (ele/ela/coisa)",
    "verb": "will be (será/estará)",
    "play1": "Will It be",
    "pron1": "Uíl ít bí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ele será/estará?"
  },
  {
    "tense": "Future",
    "form": "Negative Question",
    "subject": "It not (ele/ela/coisa não)",
    "verb": "will be (será/estará)",
    "play1": "Will It not be",
    "pron1": "Uíl ít nót bí",
    "play2": "Won't It be",
    "pron2": "Uôunt ít bí",
    "hint": "Ex: ele não será/estará?"
  },
  {
    "tense": "Future",
    "form": "Affirmative",
    "subject": "We (nós)",
    "verb": "will be (seremos/estaremos)",
    "play1": "We will be",
    "pron1": "uí uíl bí",
    "play2": "We'll be",
    "pron2": "uíll bí",
    "hint": "Ex: nós seremos/estaremos"
  },
  {
    "tense": "Future",
    "form": "Negative",
    "subject": "We (nós)",
    "verb": "will not be (não seremos/estaremos)",
    "play1": "We will not be",
    "pron1": "uí uíl nót bí",
    "play2": "Won't We be",
    "pron2": "Uôunt uí bí",
    "hint": "Ex: nós não seremos/estaremos"
  },
  {
    "tense": "Future",
    "form": "Question",
    "subject": "We (nós)",
    "verb": "will be (seremos/estaremos)",
    "play1": "Will We be",
    "pron1": "Uíl uí bí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: nós seremos/estaremos?"
  },
  {
    "tense": "Future",
    "form": "Negative Question",
    "subject": "We not (nós não)",
    "verb": "will be (seremos/estaremos)",
    "play1": "Will We not be",
    "pron1": "Uíl uí nót bí",
    "play2": "Won't We be",
    "pron2": "Uôunt uí bí",
    "hint": "Ex: nós não seremos/estaremos?"
  },
  {
    "tense": "Future",
    "form": "Affirmative",
    "subject": "They (eles/elas)",
    "verb": "will be (serão/estarão)",
    "play1": "They will be",
    "pron1": "dêir uíl bí",
    "play2": "They'll be",
    "pron2": "dêill bí",
    "hint": "Ex: eles serão/estarão"
  },
  {
    "tense": "Future",
    "form": "Negative",
    "subject": "They (eles/elas)",
    "verb": "will not be (não serão/estarão)",
    "play1": "They will not be",
    "pron1": "dêir uíl nót bí",
    "play2": "Won't They be",
    "pron2": "Uôunt dêir bí",
    "hint": "Ex: eles não serão/estarão"
  },
  {
    "tense": "Future",
    "form": "Question",
    "subject": "They (eles/elas)",
    "verb": "will be (serão/estarão)",
    "play1": "Will They be",
    "pron1": "Uíl dêir bí",
    "play2": "",
    "pron2": "",
    "hint": "Ex: eles serão/estarão?"
  },
  {
    "tense": "Future",
    "form": "Negative Question",
    "subject": "They not (eles/elas não)",
    "verb": "will be (serão/estarão)",
    "play1": "Will They not be",
    "pron1": "Uíl dêir nót bí",
    "play2": "Won't They be",
    "pron2": "Uôunt dêir bí",
    "hint": "Ex: eles não serão/estarão?"
  },
  {
    "tense": "Perfect",
    "form": "Affirmative",
    "subject": "I (eu)",
    "verb": "have been (tenho sido/estado)",
    "play1": "I have been",
    "pron1": "ái rév bín",
    "play2": "I've been",
    "pron2": "I've bín",
    "hint": "Ex: eu tenho sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Negative",
    "subject": "I (eu)",
    "verb": "have not been (não tenho sido/estado)",
    "play1": "I have not been",
    "pron1": "ái rév nót bín",
    "play2": "I haven't been",
    "pron2": "ái rêvent bín",
    "hint": "Ex: eu não tenho sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Question",
    "subject": "I (eu)",
    "verb": "have been (tenho sido/estado)",
    "play1": "Have I been",
    "pron1": "Rév ái bín",
    "play2": "",
    "pron2": "",
    "hint": "Ex: eu tenho sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Negative Question",
    "subject": "I not (eu não)",
    "verb": "have been (tenho sido/estado)",
    "play1": "Have I not been",
    "pron1": "Rév ái nót bín",
    "play2": "Haven't I been",
    "pron2": "Rêvent ái bín",
    "hint": "Ex: eu não tenho sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Affirmative",
    "subject": "You (você/vocês)",
    "verb": "have been (têm sido/estado)",
    "play1": "You have been",
    "pron1": "iú rév bín",
    "play2": "You've been",
    "pron2": "You've bín",
    "hint": "Ex: você/vocês têm sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Negative",
    "subject": "You (você/vocês)",
    "verb": "have not been (não têm sido/estado)",
    "play1": "You have not been",
    "pron1": "iú rév nót bín",
    "play2": "You haven't been",
    "pron2": "iú rêvent bín",
    "hint": "Ex: você/vocês não têm sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Question",
    "subject": "You (você/vocês)",
    "verb": "have been (têm sido/estado)",
    "play1": "Have You been",
    "pron1": "Rév iú bín",
    "play2": "",
    "pron2": "",
    "hint": "Ex: você/vocês têm sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Negative Question",
    "subject": "You not (você/vocês não)",
    "verb": "have been (têm sido/estado)",
    "play1": "Have You not been",
    "pron1": "Rév iú nót bín",
    "play2": "Haven't You been",
    "pron2": "Rêvent iú bín",
    "hint": "Ex: você/vocês não têm sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Affirmative",
    "subject": "He (ele)",
    "verb": "has been (tem sido/estado)",
    "play1": "He has been",
    "pron1": "rí réz bín",
    "play2": "He's been",
    "pron2": "ríz bín",
    "hint": "Ex: ele tem sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Negative",
    "subject": "He (ele)",
    "verb": "has not been (não tem sido/estado)",
    "play1": "He has not been",
    "pron1": "rí réz nót bín",
    "play2": "He hasn't been",
    "pron2": "rí rézent bín",
    "hint": "Ex: ele não tem sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Question",
    "subject": "He (ele)",
    "verb": "has been (tem sido/estado)",
    "play1": "Has He been",
    "pron1": "Réz rí bín",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ele tem sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Negative Question",
    "subject": "He not (ele não)",
    "verb": "has been (tem sido/estado)",
    "play1": "Has He not been",
    "pron1": "Réz rí nót bín",
    "play2": "Hasn't He been",
    "pron2": "Rézent rí bín",
    "hint": "Ex: ele não tem sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Affirmative",
    "subject": "She (ela)",
    "verb": "has been (tem sido/estado)",
    "play1": "She has been",
    "pron1": "xí réz bín",
    "play2": "She's been",
    "pron2": "xíz bín",
    "hint": "Ex: ela tem sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Negative",
    "subject": "She (ela)",
    "verb": "has not been (não tem sido/estado)",
    "play1": "She has not been",
    "pron1": "xí réz nót bín",
    "play2": "She hasn't been",
    "pron2": "xí rézent bín",
    "hint": "Ex: ela não tem sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Question",
    "subject": "She (ela)",
    "verb": "has been (tem sido/estado)",
    "play1": "Has She been",
    "pron1": "Réz xí bín",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ela tem sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Negative Question",
    "subject": "She not (ela não)",
    "verb": "has been (tem sido/estado)",
    "play1": "Has She not been",
    "pron1": "Réz xí nót bín",
    "play2": "Hasn't She been",
    "pron2": "Rézent xí bín",
    "hint": "Ex: ela não tem sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Affirmative",
    "subject": "It (ele/ela/coisa)",
    "verb": "has been (tem sido/estado)",
    "play1": "It has been",
    "pron1": "ít réz bín",
    "play2": "It's been",
    "pron2": "íts bín",
    "hint": "Ex: ele tem sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Negative",
    "subject": "It (ele/ela/coisa)",
    "verb": "has not been (não tem sido/estado)",
    "play1": "It has not been",
    "pron1": "ít réz nót bín",
    "play2": "It hasn't been",
    "pron2": "ít rézent bín",
    "hint": "Ex: ele não tem sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Question",
    "subject": "It (ele/ela/coisa)",
    "verb": "has been (tem sido/estado)",
    "play1": "Has It been",
    "pron1": "Réz ít bín",
    "play2": "",
    "pron2": "",
    "hint": "Ex: ele tem sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Negative Question",
    "subject": "It not (ele/ela/coisa não)",
    "verb": "has been (tem sido/estado)",
    "play1": "Has It not been",
    "pron1": "Réz ít nót bín",
    "play2": "Hasn't It been",
    "pron2": "Rézent ít bín",
    "hint": "Ex: ele não tem sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Affirmative",
    "subject": "We (nós)",
    "verb": "have been (temos sido/estado)",
    "play1": "We have been",
    "pron1": "uí rév bín",
    "play2": "We've been",
    "pron2": "We've bín",
    "hint": "Ex: nós temos sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Negative",
    "subject": "We (nós)",
    "verb": "have not been (não temos sido/estado)",
    "play1": "We have not been",
    "pron1": "uí rév nót bín",
    "play2": "We haven't been",
    "pron2": "uí rêvent bín",
    "hint": "Ex: nós não temos sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Question",
    "subject": "We (nós)",
    "verb": "have been (temos sido/estado)",
    "play1": "Have We been",
    "pron1": "Rév uí bín",
    "play2": "",
    "pron2": "",
    "hint": "Ex: nós temos sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Negative Question",
    "subject": "We not (nós não)",
    "verb": "have been (temos sido/estado)",
    "play1": "Have We not been",
    "pron1": "Rév uí nót bín",
    "play2": "Haven't We been",
    "pron2": "Rêvent uí bín",
    "hint": "Ex: nós não temos sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Affirmative",
    "subject": "They (eles/elas)",
    "verb": "have been (têm sido/estado)",
    "play1": "They have been",
    "pron1": "dêir rév bín",
    "play2": "They've been",
    "pron2": "They've bín",
    "hint": "Ex: eles têm sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Negative",
    "subject": "They (eles/elas)",
    "verb": "have not been (não têm sido/estado)",
    "play1": "They have not been",
    "pron1": "dêir rév nót bín",
    "play2": "They haven't been",
    "pron2": "dêir rêvent bín",
    "hint": "Ex: eles não têm sido/estado"
  },
  {
    "tense": "Perfect",
    "form": "Question",
    "subject": "They (eles/elas)",
    "verb": "have been (têm sido/estado)",
    "play1": "Have They been",
    "pron1": "Rév dêir bín",
    "play2": "",
    "pron2": "",
    "hint": "Ex: eles têm sido/estado?"
  },
  {
    "tense": "Perfect",
    "form": "Negative Question",
    "subject": "They not (eles/elas não)",
    "verb": "have been (têm sido/estado)",
    "play1": "Have They not been",
    "pron1": "Rév dêir nót bín",
    "play2": "Haven't They been",
    "pron2": "Rêvent dêir bín",
    "hint": "Ex: eles não têm sido/estado?"
  }
];
